# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-28 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countrylanguage',
            table='countryLanguage',
        ),
    ]
