# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-01-29 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_auto_20250128_0745'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='countrylanguage',
            table='countrylanguage',
        ),
    ]
